### PR TITLE
Remove cluster creation from helm

### PR DESCRIPTION
**Pull request by IDerr**
Remove cluster creation from Helm,
a cluster and a standalone redis is created when crd is installed,
I think it's better to let the user decide if they want to create one, or let them the choice to do it. (Perhaps in another cluster)

Thanks a lot for your work

### CODE REVIEW

**Comment by DoubleJ213** [comment]
OK.Shall we divide the pre helm chart into two parts or add a cluster and a standalone charts @houseonline @gaoshengL

**Comment by IDerr** [comment]
yes perhaps, or we could use some variables to deploy or not the cluster

**Comment by DoubleJ213** [comment]
You can use --set type=cluster or type=standby to choice which kind of redis to be installed .
such as only install RedisCluster by using the command  $ helm install --namespace=redis [RELEASE_NAME] td-redis-operator/td-redis-operator --set type=cluster

For more differents about  RedisCluster and RedisStandby
https://github.com/tongdun/td-redis-operator/wiki/Principle-of-Main-and-Standby-Realization#architecture
https://github.com/tongdun/td-redis-operator/wiki/Principles-of-Cluster-Implementation#architecture

**Comment by IDerr** [comment]
perfect, i think by default we should add a type none, to deploy 0 cluster (if we want a cluster in another namespace for example)

**Comment by DoubleJ213** [comment]
A chart deploy without cr maybe not friendly to new users. If you want to deploy operator and cr in different ns , you can modify it in your branch ?

**Comment by DoubleJ213** [comment]
btw if use --set type=none now,  no redis cr will  be deployed. the redis cr deployed only if you input --set type=cluster\standby\all  or noting to be set

**Comment by IDerr** [comment]
oh ok, great, i'll do something like this

**Comment by IDerr** [comment]
It's working great for me 
i think you could merge this pr

**Pull request merged**
